[theme]
primaryColor = "#00ffff"
backgroundColor = "#0f2027"
secondaryBackgroundColor = "#1a3a3a"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[browser]
gatherUsageStats = false
